app/routes/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from flask_login import login_user, logout_user, login_required, current_user
from flask_paginate import Pagination, get_page_parameter
from app.models.models import Post, User, Log, Tag, Concert, ConcertImage, PostImage, Counter, Note, NoteImage
from app.extensions import db, login_manager, limiter
from app.forms.forms import *
from datetime import datetime, date, timedelta
import os
from werkzeug.security import generate_password_hash, check_password_hash
import json
import markdown
import re

# blueprintの作成
main_bp = Blueprint("main", __name__)
# ログインマネージャー
login_manager.login_view = "main.login"
# ファイルアップロード
upload_folder = "app/static/uploads"

def convert_youtube_url_to_embed(url):
    match = re.search(r"(?:https?://)?(?:www\.)?youtube\.com/watch\?v=([^\s&]+)", url)
    if match:
        video_id = match.group(1)
        return f"https://www.youtube.com/embed/{video_id}"
    match = re.search(r"(?:https?://)?youtu\.be/([^\s?&]+)", url)
    if match:
        video_id = match.group(1)
        return f"https://www.youtube.com/embed/{video_id}"
    print("error")
    return None

@main_bp.route("/")
def index():
    session.permanent = True
    today = date.today()
    daily = Counter.query.filter_by(date=today).first()
    last_count = Counter.query.order_by(Counter.date.desc()).first()
    user_count = last_count.user_count if last_count else 0
    if not daily:
        daily = Counter(date=today, access_count=0, user_count=user_count)
        db.session.add(daily)
        db.session.commit()
    now = datetime.now()
    last_visit = session.get("last_visit")
    if not last_visit:
        daily.user_count += 1
        daily.access_count += 1
        session["last_visit"] = now.isoformat()
    else:
        last_visit_time = datetime.fromisoformat(last_visit)
        if now - last_visit_time > timedelta(hours=1):
            daily.access_count += 1
            session["last_visit"] = now.isoformat()
    db.session.commit()

    posts = Post.query.order_by(Post.date.desc()).limit(5).all()
    for post in posts:
        post.date_str = f"{post.date.year}年{post.date.month}月{post.date.day}日"
    concert = Concert.query.filter_by(top=True).first()
    note = Note.query.order_by(Note.date.desc()).limit(5).all()
    for page in note:
        page.date_str = f"{page.date.year}年{page.date.month}月{page.date.day}日"
    
    return render_template("index.html", posts=posts, concert=concert, note=note)

@main_bp.route("/news")
def news():
    page = request.args.get(get_page_parameter(), type=int, default=1)
    per_page = 10
    all_posts = Post.query.order_by(Post.date.desc()).all()
    for post in all_posts:
        post.date_str = f"{post.date.year}年{post.date.month}月{post.date.day}日"
    total = len(all_posts)
    posts = all_posts[(page - 1) * per_page: page * per_page]
    pagination = Pagination(page=page, per_page=per_page, total=total, css_framework="boostrap5")
    return render_template("news.html", posts=posts, pagination=pagination)

@main_bp.route("/news/<int:id>")
def article(id):
    article = Post.query.get_or_404(id)
    article.view_count += 1
    db.session.commit()
    article.text = markdown.markdown(article.content, extensions=['nl2br'])
    print(article.text)
    article.date_str = f"{article.date.year}年{article.date.month}月{article.date.day}日"
    return render_template("article.html", article=article)

@main_bp.route("/note")
def note():
    page_count = request.args.get(get_page_parameter(), type=int, default=1)
    per_page = 10
    all_page = Note.query.order_by(Note.date.desc()).all()
    for page in all_page:
        page.date_str = f"{page.date.year}年{page.date.month}月{page.date.day}日"
    total = len(all_page)
    note = all_page[(page_count - 1) * per_page: page_count * per_page]
    pagination = Pagination(page=page_count, per_page=per_page, total=total, css_framework="boostrap5")
    return render_template("note.html", note=note, pagination=pagination)

@main_bp.route("/note/<int:id>")
def page(id):
    page = Note.query.get_or_404(id)
    page.view_count += 1
    db.session.commit()
    page.text = markdown.markdown(page.content, extensions=['nl2br'])
    page.date_str = f"{page.date.year}年{page.date.month}月{page.date.day}日"
    return render_template("page.html", page=page)

@main_bp.route("/concert")
def concerts():
    future_concerts = Concert.query.filter_by(end=False).order_by(Concert.date.desc()).all()
    end_concerts = Concert.query.filter_by(end=True).order_by(Concert.date.desc()).all()
    return render_template("concerts.html", future_concerts=future_concerts, end_concerts=end_concerts)

@main_bp.route("/concert/<string:url>")
def concert(url):
    concert = Concert.query.filter_by(url=url).first()
    print(concert)
    concert.view_count += 1
    db.session.commit()
    concert.text = markdown.markdown(concert.text, extensions=['nl2br'])
    return render_template("concert.html", concert=concert)

@main_bp.route("/joinus")
def join_us():
    return render_template("joinus.html")

@main_bp.route("/admin")
@login_required
def admin():
    count = Counter.query.order_by(Counter.date.desc()).first()
    return render_template("admin.html", count=count)

@main_bp.route("/admin/login", methods=["GET", "POST"])
@limiter.limit("60/hour;5/minute", methods=["POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        id = form.id.data
        pw = form.pw.data
        user = User.query.filter_by(id=id).first()
        if user and check_password_hash(user.pw, pw):
            login_user(user)
            new_log = Log(user_id=str(current_user.id), 
                          action_type="login")
            db.session.add(new_log)
            db.session.commit()
            return redirect(url_for("main.admin"))
        flash("idまたはpwが間違っています")
    return render_template("login.html", form=form)

@main_bp.route("/admin/logout")
@login_required
def logout():
    new_log = Log(user_id=str(current_user.id), 
                  action_type="logout")
    logout_user()
    db.session.add(new_log)
    db.session.commit()
    return redirect(url_for("main.login"))

@main_bp.route("/admin/user")
@login_required
def user():
    users = User.query.all()
    return render_template("user_list.html", users=users)

@main_bp.route("/admin/post")
@login_required
def post():
    posts = Post.query.all()
    return render_template("post_list.html", posts=posts)

@main_bp.route("/admin/note")
@login_required
def kawagutisan():
    note = Note.query.all()
    return render_template("note_list.html", note=note)

@main_bp.route("/admin/concert")
@login_required
def concert_list():
    concerts = Concert.query.all()
    return render_template("concert_list.html", concerts=concerts)

@main_bp.route("/admin/user/create", methods=["GET", "POST"])
@login_required
def create_user():
    form = UserForm()
    if form.validate_on_submit():
        id = form.id.data
        name = form.name.data
        pw = form.pw.data
        hashed_pw = generate_password_hash(pw)
        new_user = User(id=id, name=name, pw=hashed_pw)
        db.session.add(new_user)
        db.session.commit()
        new_log = Log(user_id=str(current_user.id), 
                      action_type="create_user", 
                      target_table="users", 
                      target_id=new_user.id)
        db.session.add(new_log)
        db.session.commit()
        flash("ユーザー登録完了")
        return redirect(url_for("main.user"))
    return render_template("create_user.html", form=form)

@main_bp.route("/admin/user/edit/<string:id>", methods=["GET", "POST"])
@login_required
def edit_user(id):
    user = User.query.get_or_404(id)
    form = EditUser(obj=user)
    if request.method == "GET":
        form.pw.data = ""
    if form.validate_on_submit():
        old_id = user.id
        old_name = user.name
        old_pw = user.pw
        user.id = form.id.data
        user.name = form.name.data
        if form.pw.data:
            user.pw = generate_password_hash(form.pw.data)
        db.session.commit()
        new_log = Log(user_id=str(current_user.id), 
                      action_type="edit_user", 
                      target_table="users", 
                      target_id=old_id, 
                      text=json.dumps({
                          "old_id" : old_id, 
                          "new_id" : user.id, 
                          "old_name" : old_name, 
                          "new_name" : user.name, 
                          "old_pw" : old_pw, 
                          "new_pw" : user.pw
                        }, 
                        ensure_ascii=False))
        db.session.add(new_log)
        db.session.commit()
        flash("ユーザー情報編集完了")
        return redirect(url_for("main.user"))
    return render_template("edit_user.html", form=form)

@main_bp.route("/admin/user/delete/<string:id>")
@login_required
def delete_user(id):
    user = User.query.get_or_404(id)
    if user.id == current_user.id:
        flash("自分自身は削除できません。")
        return redirect(url_for("main.user"))
    new_log = Log(user_id=str(current_user.id), 
                  action_type="delete_user", 
                  target_table="users", 
                  target_id=user.id)
    db.session.delete(user)
    db.session.add(new_log)
    db.session.commit()
    flash("ユーザー削除完了")
    return redirect(url_for("main.user"))

@main_bp.route("/admin/post/create", methods=["GET", "POST"])
@login_required
def create_post():
    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        content = form.content.data
        media = form.media.data
        date = form.date.data
        if media == "youtube":
            url = convert_youtube_url_to_embed(form.youtube.data)
        else:
            url = None
        tag_names = [t.strip() for t in form.tags.data.split(",") if t.strip()]
        tags = []

app/templates/admin.html
{% extends "layout_admin.html" %}
{% block title %}Admin | アンサンブル・シマエナガ{% endblock %}

{% block content %}
<div class="container py-5">
    <h1 class="fs-2 mb-4">Admin</h1>

    <!-- ユーザー情報 -->
    <div class="mb-4">
        <p><strong>ログインユーザー:</strong> {{ current_user.name }}    <a href="{{ url_for('main.edit_user', id=current_user.id) }}">編集</a></p>
        <p><strong>アクセスユーザー数:</strong> {{ count.user_count }}</p>
        <p><strong>総アクセス数:</strong> {{ count.access_count }}</p>
    </div>

    <!-- フラッシュメッセージ -->
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="alert alert-warning" role="alert">
                <ul class="mb-0">
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
    {% endwith %}

    <!-- 管理メニュー -->
    <div class="row g-3">
        <div class="col-md-6">
            <a href="{{ url_for('main.index') }}" class="btn btn-outline-dark w-100">🏠 トップページ</a>
        </div>

        <div class="col-md-6">
            <a href="{{ url_for('main.post') }}" class="btn btn-outline-dark w-100">📝 投稿一覧</a>
        </div>

        <div class="col-md-6">
            <a href="{{ url_for('main.concert_list') }}" class="btn btn-outline-dark w-100">🎵 演奏会リスト</a>
        </div>

        <div class="col-md-6">
            <a href="{{ url_for('main.kawagutisan') }}" class="btn btn-outline-dark w-100">🌸 Kawagutisan</a>
        </div>

        {% if current_user.id == "taiyo" %}
        <div class="col-md-6">
            <a href="/management" class="btn btn-outline-secondary w-100">🛠 Flask-admin</a>
        </div>
        
        <div class="col-md-6">
            <a href="{{ url_for('main.user') }}" class="btn btn-outline-dark w-100 ">👥 ユーザー一覧</a>
        </div>
        {% endif %}

        <div class="col-md-6">
            <a href="{{ url_for('main.logout') }}" class="btn btn-danger w-100">🚪 ログアウト</a>
        </div>

    </div>
</div>
{% endblock %}

app/templates/concert_list.html
{% extends "layout_admin.html" %}
{% block title %} 演奏会 | アンサンブル・シマエナガ {% endblock %}

{% block content %}
<div class="container py-5">
    <h1 class="fs-2 mb-4">演奏会</h1>

    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="alert alert-info">
                <ul class="mb-0 list-unstyled">
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
    {% endwith %}

    <a href="{{ url_for('main.create_concert') }}" class="btn btn-primary mb-4">＋ 演奏会を追加</a>

    {% if concerts %}
    <ul class="list-group">
        {% for concert in concerts %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
            <span>
                <strong>{{ concert.id }}</strong> : {{ concert.title }}
            </span>
            {% if current_user.id == "taiyo" %}
            <span>
                <a href="{{ url_for('main.edit_concert', id=concert.id) }}" class="btn btn-sm btn-outline-secondary me-2">編集</a>
                <a href="{{ url_for('main.delete_concert', id=concert.id) }}" class="btn btn-sm btn-outline-danger">削除</a>
            </span>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>演奏会の投稿はまだありません。</p>
    {% endif %}
</div>
{% endblock %}

app/templates/concerts.html
{% extends "layout.html" %}
{% block title %} 演奏会情報 | アンサンブル・シマエナガ {% endblock %}
{% block content %}
  <div class="container-fluid py-4 pb-md-3 pt-md-5">
    {% set total = future_concerts|length %}
    {% for concert in future_concerts %}
      {% if loop.index0 % 3 == 0 %}
        <div class="row justify-content-center align-items-center text-center mb-4">
      {% endif %}

      <div class="col-12 col-md-3">
        <p class="fs-5 ps-2 bottom-line mb-3 text-start">{{ concert.title }}</p>
        <div class="px-2 mb-3">
          <a href="{{ url_for('main.concert', url=concert.url) }}">
            <img src="{{ url_for('static', filename='uploads/' ~ concert.images[0].path) }}" alt="" class="concert-image">
          </a>
        </div>
      </div>
      {% if loop.index0 % 3 == 2 or loop.last %}
        {% if loop.last and total % 3 != 0 %}
          {% set remainder = 3 - (total % 3) %}
          {% for i in range(remainder) %}
            <div class="col-12 col-md-3"></div>
          {% endfor %}
        {% endif %}
        </div>
      {% endif %}
    {% endfor %}

		<div class="row justify-content-center align-items-center text-center">
      <p class="col-12 col-md-10 fw-100 fs-2 lh-1 font-gothic text-start mb-3 mb-md-3 py-2">過去の演奏会</p>
		</div>
		{% set total = end_concerts|length %}
    {% for concert in end_concerts %}
      {% if loop.index0 % 3 == 0 %}
        <div class="row justify-content-center align-items-center text-center mb-4">
      {% endif %}

      <div class="col-12 col-md-3">
        <p class="fs-5 ps-2 bottom-line mb-3 text-start">{{ concert.title }}</p>
        <div class="px-2 mb-3">
          <a href="{{ url_for('main.concert', url=concert.url) }}">
            <img src="{{ url_for('static', filename='uploads/' ~ concert.images[0].path) }}" alt="" class="concert-image">
          </a>
        </div>
      </div>
			
			<!-- 演奏会増えてきたら東混みたいにaタグでタイトルだけ出す？ -->

      {% if loop.index0 % 3 == 2 or loop.last %}
        {% if loop.last and total % 3 != 0 %}
          {% set remainder = 3 - (total % 3) %}
          {% for i in range(remainder) %}
            <div class="col-12 col-md-3"></div>
          {% endfor %}
        {% endif %}
        </div>
      {% endif %}
    {% endfor %}
  </div>
{% endblock %}

app/templates/create_post.html
{% extends "layout_admin.html" %}
{% block title %} ニュース投稿 | アンサンブル・シマエナガ {% endblock %}

{% block content %}
<div class="container py-5">
    <h1 class="fs-2 mb-4">投稿</h1>

    <form method="post" novalidate enctype="multipart/form-data">
        {{ form.hidden_tag() }}

        <!-- タイトル -->
        <div class="mb-3">
            {{ form.title.label(class="form-label") }}
            {{ form.title(class="form-control") }}
            {% for error in form.title.errors %}
                <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>

        <!-- 本文 -->
        <div class="mb-3">
            {{ form.content.label(class="form-label") }}
            {{ form.content(class="form-control", id="text-area") }}
            {% for error in form.content.errors %}
                <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>

        <!-- メディア種別選択 -->
        <div class="mb-3">
            {{ form.media.label(class="form-label") }}
            {{ form.media(class="form-select list-unstyled") }}
            {% for error in form.media.errors %}
                <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>

        <!-- ファイルアップロード -->
        <div id="file-field" class="mb-3" style="display: none;">
            {{ form.file.label(class="form-label") }}
            {{ form.file(class="form-control") }}
            {% for error in form.file.errors %}
                <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>

        <!-- YouTube URL -->
        <div id="youtube-field" class="mb-3" style="display: none;">
            {{ form.youtube.label(class="form-label") }}
            {{ form.youtube(class="form-control") }}
            {% for error in form.youtube.errors %}
                <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>

        <!-- 日付 -->
        <div class="mb-3">
            {{ form.date.label(class="form-label") }}
            {{ form.date(class="form-control") }}
            {% for error in form.date.errors %}
                <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>

        <!-- タグ -->
        <div class="mb-3">
            {{ form.tags.label(class="form-label") }}
            {{ form.tags(class="form-control") }}
            {% for error in form.tags.errors %}
                <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>

        <!-- 送信 -->
        <div class="mb-3">
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>
</div>

<!-- JS -->
<script src="{{ url_for('static', filename='js/create_post.js') }}"></script>
<script src="https://unpkg.com/autosize@4.0.2/dist/autosize.min.js"></script>
<script>
    autosize(document.getElementById('text-area'));
</script>
{% endblock %}

app/templates/create_user.html
{% extends "layout_admin.html" %}
{% block title %} ユーザー追加 | アンサンブル・シマエナガ {% endblock %}

{% block content %}
<div class="container py-5">
    <h1 class="fs-2 mb-4">ユーザー追加</h1>

    <form method="post" novalidate>
        {{ form.hidden_tag() }}

        <!-- ID -->
        <div class="mb-3">
            {{ form.id.label(class="form-label") }}
            {{ form.id(class="form-control") }}
            {% for error in form.id.errors %}
                <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>

        <!-- 名前 -->
        <div class="mb-3">
            {{ form.name.label(class="form-label") }}
            {{ form.name(class="form-control") }}
            {% for error in form.name.errors %}
                <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>

        <!-- パスワード -->
        <div class="mb-3">
            {{ form.pw.label(class="form-label") }}
            {{ form.pw(class="form-control", type="password") }}
            {% for error in form.pw.errors %}
                <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>

        <!-- 送信 -->
        <div class="mb-3">
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>
</div>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="ja">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %} アンサンブル・シマエナガ {% endblock %}</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/reset-min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/layout.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
	<link rel="icon" href="{{ url_for('static', filename='images/favicon.ico') }}">
	<link rel="apple-touch-icon" href="{{ url_for('static', filename='images/apple-touch-icon.jpg') }}">
	<link rel="manifest" href="{{ url_for('static', filename='manifest.json') }}">
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&display=swap" rel="stylesheet">
	{% block head %}{% endblock %}
</head>
<body>
	<header class="p-1 px-md-5 py-md-2">
		<div class="header-contents">
			<nav class="navbar navbar-expand-md">
        <div class="container-fluid d-flex flex-wrap align-items-center">
          <button class="navbar-toggler no-style-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="flex-grow-1 d-flex justify-content-center justify-content-md-start">
            <a class="navbar-brand" href="{{ url_for('main.index') }}"><img src="{{ url_for('static', filename='images/logo.png') }}" alt=""></a>
          </div>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
              <li class="nav-item"><a class="nav-link" href="{{ url_for('main.index') }}">ホーム</a></li>
              <li class="nav-item"><a class="nav-link" href="{{ url_for('main.news') }}">ニュース</a></li>
              <li class="nav-item"><a class="nav-link" href="{{ url_for('main.concert', id=1) }}">演奏会情報</a></li>
              <li class="nav-item"><a class="nav-link" href="{{ url_for('main.join_us') }}">団員募集</a></li>
              <!-- <li><a href="">お問い合わせ</a></li> -->
            </ul>
          </div>
        </div>
			</nav>
		</div>
	</header>
	<main>
		{% block content %}{% endblock %}
	</main>
	<footer class="pt-4 pt-md-5 pb-2">
    <div class="container">
      <div class="row mx-auto">
        <div class="col-12 col-md-6 row1">
          <ul class="sns d-flex justify-content-center gap-3 list-unstyled">
            <li><a href="https://x.com/Ens_Shimaenaga?s=20"><i class="fa-brands fa-x-twitter"></i>X</a></li>
            <li><a href="https://www.instagram.com/ens_shimaenaga/"><i class="fa-brands fa-instagram"></i>Instagram</a></li>
            <li><a href="https://www.youtube.com/@Ens_Shimaenaga"><i class="fa-brands fa-youtube"></i>Youtube</a></li>
          </ul>
        </div>
        <div class="col-12 col-md-6 text-center">
          <p class="fs-5 mb-2">混声合唱団アンサンブル・シマエナガ</p>
          <p class="m-0">Mail:ensemble.shimaenaga@gmail.com</p>
          <p class="m-0">TEL:×××-××××-××××</p>
        </div>
      </div>
    </div>
  	<p class="rights"><small>© 2025 Ensemble shimaenaga. All rights reserved.</small></p>
	</footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

app/templates/note.html
{% extends "layout.html" %}
{% block title %} 音楽監督のつぶやき | アンサンブル・シマエナガ {% endblock %}
{% block content %}

  <div class="container-fluid py-3 py-md-5">
    <div class="row justify-content-center align-items-center text-center">
      <p class="col-12 col-md-10 fw-100 fs-2 lh-1 font-gothic text-start mb-1 mb-md-3 pl-40px py-2">音楽監督のつぶやき💭</p>
      <div class="col-12 col-md-10">
        {% for page in note %}
          <div class="button news-box d-flex align-items-center">
            <a href="{{ url_for('main.page', id=page.id) }}" class="w-100">
              <div class="text-start m-100 w-100 pl-40px">
                <p class="fs-6 fs-md-5 mb-1 mb-md-2 text-truncate text-black">{{ page.title }}</p>
                <p class="fs-14px m-0 text-black">{{ page.date_str }}</p>
              </div>
            </a>
          </div>
        {% endfor %}
      </div>
    </div>

    
  </div>
  <div class="pagination-box d-flex justify-content-center ">
    {{ pagination.links }}
  </div>
  
{% endblock %}

app/templates/post_list.html
{% extends "layout_admin.html" %}
{% block title %} 投稿リスト | アンサンブル・シマエナガ {% endblock %}

{% block content %}
<div class="container py-5">
    <h1 class="fs-2 mb-4">投稿リスト</h1>

    <!-- フラッシュメッセージ -->
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="alert alert-info">
                <ul class="mb-0 list-unstyled">
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
    {% endwith %}

    <a href="{{ url_for('main.create_post') }}" class="btn btn-primary mb-4">＋ 投稿を追加</a>

    {% if posts %}
    <ul class="list-group">
        {% for post in posts %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
            <span>
                <strong>{{ post.id }}</strong> : {{ post.title }}
            </span>
            {% if current_user.id == "taiyo" %}
            <span>
                <a href="{{ url_for('main.edit_post', id=post.id) }}" class="btn btn-sm btn-outline-secondary me-2">編集</a>
                <a href="{{ url_for('main.delete_post', id=post.id) }}" class="btn btn-sm btn-outline-danger">削除</a>
            </span>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>投稿がありません。</p>
    {% endif %}
</div>
{% endblock %}

app/templates/user_list.html
{% extends "layout_admin.html" %}
{% block title %} ユーザーリスト | アンサンブル・シマエナガ {% endblock %}

{% block content %}
<div class="container py-5">
  <h1 class="fs-2 mb-4">ユーザーリスト</h1>

  {% with messages = get_flashed_messages() %}
    {% if messages %}
      <div class="alert alert-info">
        <ul class="mb-0">
          {% for message in messages %}
            <li>{{ message }}</li>
          {% endfor %}
        </ul>
      </div>
    {% endif %}
  {% endwith %}

  {% if current_user.id == "taiyo" %}
    <a href="{{ url_for('main.create_user') }}" class="btn btn-primary mb-3">ユーザー追加</a>
  {% endif %}

  <ul class="list-group">
    {% for user in users %}
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <div>{{ user.id }} : {{ user.name }}</div>
        {% if current_user.id == "taiyo" %}
          <div>
            <a href="{{ url_for('main.edit_user', id=user.id) }}" class="btn btn-sm btn-outline-secondary me-2">編集</a>
            <a href="{{ url_for('main.delete_user', id=user.id) }}" class="btn btn-sm btn-outline-danger">削除</a>
          </div>
        {% endif %}
      </li>
    {% endfor %}
  </ul>
</div>
{% endblock %}